name: "Webhook"
guid: "71552A5A-5C5C-4350-A2AE-EBE451A30173"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-webhook.png"
version: 16
targetAbi: "10.9.10.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Sends notifications."
description: >
  Sends notifications to destinations via webhooks.

category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.Webhook.dll"
  - "Handlebars.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Cryptography.dll"
  - "MQTTnet.dll"
  - "MQTTnet.Extensions.ManagedClient.dll"
changelog: |-
  - Expose RemoteEndPoint & SessionInfo Variables (#275) @chiragkrishna
  - Fix SessionStart double notifications (#272) @chiragkrishna
  - Add option for Item type videos (#274) @chiragkrishna
  - Add RemoteEndPoint variable (#273) @chiragkrishna
  - Fix duplicate and wrong notification types for Pushover templates (#270) @Luka-He
  - ntfy.sh: Template Optimizations (#268) @v3DJG6GL

  ### Documentation updates ###
  - Update README.md (#271) @chiragkrishna

  ### Dependency updates ###
  - chore(deps): update dependency mailkit to v4.7.1.1 (#263) @renovate
